version: '3'
services:
  n8n:
    image: n8nio/n8n
    container_name: n8n
    volumes:
      - ./n8n/workflow.json:/data/workflow.json
      - ./videos:/videos
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=user
      - N8N_BASIC_AUTH_PASSWORD=pass
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true  # Fix the permissions warning
